### ISSUE TITLE
Boss website new footer is not responsive in both laptop as well as mobile.

### ISSUE THREAD

**Issue by Mayank4git** [coding-blocks/boss#271] opened 2020-05-18 04:11 UTC
**The footer that has been added is not responsive at all.It is creating bad website view.**
__________________________________

![Screenshot from 2020-05-18 09-37-17](https://user-images.githubusercontent.com/26319657/82173601-77a10800-98eb-11ea-8c2f-020e498fef65.png)

**I am not able to see leaderboard of 2020 because of this footer**.website is not behaving in proper manner in any tab.Please remove that merge code of footer which is not responsive

**Comment by Mayank4git** [comment] 2020-05-18 04:13
@championswimmer please review this issue and assign bounty if there are for it.

**Comment by YashKumarVerma** [comment] 2020-05-18 04:13
Possible duplicate of #270

**Comment by Mayank4git** [comment] 2020-05-18 04:14
@YashKumarVerma but this added footer without testing making website work so bad

**Comment by YashKumarVerma** [comment] 2020-05-18 04:21
> @YashKumarVerma but this added footer without testing making website work so bad

sure it does.

**Comment by hereisnaman** [comment] 2020-05-18 14:29
closing in favor of https://github.com/coding-blocks/boss/issues/270

**Closed by hereisnaman** 2020-05-18 14:29 UTC
