### ISSUE TITLE
Gitter tab takes to boss 2019 lobby

### ISSUE THREAD

**Issue by mnb27** [coding-blocks/boss#215] opened 2020-05-15 17:53 UTC
https://boss.codingblocks.com/   
Gitter tab in navbar is linked to boss-2019-lobby instead of current 2020 lobby. I want to take this issue.
![Screenshot from 2020-05-15 23-20-36](https://user-images.githubusercontent.com/52792904/82080913-0ef73700-9703-11ea-94b4-aa80da06bf2e.png)

**Comment by sahuaman83** [comment] 2020-05-16 13:18
can i work on this issue?

**Comment by mnb27** [comment] 2020-05-17 14:20
@abhishek97

**Comment by abhishek97** [comment] 2020-05-17 14:34
Duplicate of https://github.com/coding-blocks/boss/issues/197

**Closed by abhishek97** 2020-05-17 14:34 UTC
