### ISSUE TITLE
Needs to to add discord 2020 invite link

### ISSUE THREAD

**Issue by Coding-Bee** [coding-blocks/boss#255] opened 2020-05-17 14:32 UTC
> after gitter redirecting to old link we can find old link of discord https://discord.gg/CV4fUna

> Should be updated ?

**Comment by abhishek97** [comment] 2020-05-17 14:34
Duplicate of https://github.com/coding-blocks/boss/issues/197

**Closed by abhishek97** 2020-05-17 14:34 UTC
