### ISSUE TITLE
Allow adding a claim even without adding the PR URL

### ISSUE THREAD

**Issue by till-tomorrow** [coding-blocks/boss#61] opened 2018-05-15 15:53 UTC
An error is shown when the PR URL is not given and the user tries to submit the claim. If the error has to be shown, then show it dynamically(e.g., Display message like "Field required") i.e., before the user submits the claim.

In reference to issue #49

**Comment by ananay** [comment] 2018-05-16 21:36
Duplicate of https://github.com/coding-blocks/boss/issues/56

**Closed** 2018-06-04 19:59 UTC
