### ISSUE TITLE
Can't move to next Leaderboard and Claim pages

### ISSUE THREAD

**Issue by mnb27** [coding-blocks/boss#274] opened 2020-05-18 04:52 UTC
Footer is hiding the next page button.
![Screenshot from 2020-05-18 10-10-01](https://user-images.githubusercontent.com/52792904/82175046-4a0a8d80-98f0-11ea-86e6-5e6d24bee5a7.png)
![Screenshot from 2020-05-18 10-10-09](https://user-images.githubusercontent.com/52792904/82175306-3ca1d300-98f1-11ea-8fd6-f54a74a3991e.png)

**Comment by YashKumarVerma** [comment] 2020-05-18 05:52
Possible duplicate of #270 #271

**Comment by hereisnaman** [comment] 2020-05-18 14:30
closing this in favor of https://github.com/coding-blocks/boss/issues/270

**Closed by hereisnaman** 2020-05-18 14:30 UTC
