### ISSUE TITLE
Navigation bar error

### ISSUE THREAD

**Issue by dungeonmaster51** [coding-blocks/boss#223] opened 2020-05-15 19:47 UTC
![image](https://user-images.githubusercontent.com/34394217/82090314-f98a0900-9712-11ea-8e0a-1a8c3ef67c64.png)
Static navigation bar.

**Comment by abhishek97** [comment] 2020-05-17 14:41
Duplicate of https://github.com/coding-blocks/boss/issues/217

**Closed by abhishek97** 2020-05-17 14:41 UTC
