### ISSUE TITLE
Discord Channel

### ISSUE THREAD

**Issue by Sapna2001** [coding-blocks/boss#281] opened 2020-05-18 10:38 UTC
Only the gitter channel has been mentioned on the website and it would be better if the discord channel link is also added to the website.

**Comment by prabalsingh24** [comment] 2020-05-18 11:16
Duplicate of https://github.com/coding-blocks/boss/issues/197

**Comment by ankiiitraj** [comment] 2020-05-18 15:48
Has been fixed with #292 close this. Thanks!

**Closed** 2020-06-13 15:03 UTC
