### ISSUE TITLE
ERROR: Cannot get CLAIMS ADD Page

### ISSUE THREAD

**Issue by Dhroov7** [coding-blocks/boss#57] opened 2018-05-15 11:49 UTC
![screen shot 2018-05-15 at 5 17 30 pm](https://user-images.githubusercontent.com/18377905/40054946-ef0cb270-5835-11e8-8835-b0c0c4130b38.png)

**Comment by ankurg22** [comment] 2018-05-15 17:16
Duplicate of #48

**Closed** 2018-05-16 21:07 UTC
